export enum LoadingKey {
  FS_INITIALIZING = 'FS_INITIALIZING',
  PACKAGE_INSTALLING = 'INSTALLING',
  PACKAGE_UNINSTALLING = 'UNINSTALLING',
  PACKAGE_UPDATING = 'UPDATING',
  PROJECT_CREATING = 'PROJECT_CREATING',
  PROJECT_DELETING = 'PROJECT_DELETING',
  PROJECT_RENAMING = 'PROJECT_RENAMING',
}
