export enum LoadingKey {
  PACKAGE_INSTALLING = 'INSTALLING',
  PACKAGE_UNINSTALLING = 'UNINSTALLING',
  PACKAGE_UPDATING = 'UPDATING',
  WORKSPACES_INITIALIZING = 'WORKSPACES_INITIALIZING',
  WORKSPACE_CREATING = 'WORKSPACE_CREATING',
  WORKSPACE_DELETING = 'WORKSPACE_DELETING',
  WORKSPACE_RENAMING = 'WORKSPACE_RENAMING',
  WORKSPACE_GETTING_NAMES = 'WORKSPACE_GETTING_NAMES',
}
